branch-defaults:
  staging:
    environment: captain-sky-stg
    group_suffix: null
environment-defaults:
  captain-sky-stg:
    branch: null
    repository: null
global:
  application_name: captain-sky
  branch: null
  default_ec2_keyname: captain-sky-key
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-dav
  repository: null
  sc: git
  workspace_type: Application
